package io.github.notsyncing.lightfur.entity.dsl

import io.github.notsyncing.lightfur.entity.EntityFieldInfo
import io.github.notsyncing.lightfur.entity.EntityGlobal
import io.github.notsyncing.lightfur.entity.EntityModel
import io.github.notsyncing.lightfur.sql.base.SQLPart
import io.github.notsyncing.lightfur.sql.builders.SelectQueryBuilder
import io.github.notsyncing.lightfur.sql.models.ColumnModel
import io.github.notsyncing.lightfur.sql.models.TableModel

abstract class EntityBaseDSL {
    abstract protected val builder: SQLPart

    companion object {
        @JvmStatic
        protected fun getTableModelFromEntityModel(m: EntityModel): TableModel {
            val table = TableModel()
            table.name = m.table
            table.database = m.database
            table.schema = m.schema
            table.alias = "${m.javaClass.simpleName}_${m.hashCode()}"

            return table
        }

        @JvmStatic
        protected fun getTableModelFromSubQuery(s: EntitySelectDSL): TableModel {
            val table = TableModel()
            table.subQuery = s.toSQLPart() as SelectQueryBuilder
            table.alias = "${s.javaClass.simpleName}_${s.hashCode()}"

            return table
        }

        @JvmStatic
        fun getColumnModelFromEntityFieldInfo(info: EntityFieldInfo): ColumnModel {
            val c = ColumnModel()
            c.table = EntityGlobal.tableModels[info.entity.javaClass]!!.clone()
            c.table.alias = "${info.entity.javaClass.simpleName}_${info.entity.hashCode()}"
            c.modelType = info.entity.javaClass.canonicalName
            c.column = info.dbColumn
            c.fieldName = info.name
            c.isAutoGenerated = info.dbAutoGenerated
            c.isPrimaryKey = info.dbPrimaryKey

            return c
        }
    }

    fun execute() {

    }

    open fun toSQLPart() = builder

    open fun toSQL() = builder.toString()
}