package io.github.notsyncing.lightfur.entity.dsl

import io.github.notsyncing.lightfur.entity.EntityFieldInfo
import io.github.notsyncing.lightfur.entity.EntityModel
import io.github.notsyncing.lightfur.sql.base.ExpressionBuilder
import io.github.notsyncing.lightfur.sql.base.SQLPart
import io.github.notsyncing.lightfur.sql.builders.UpdateQueryBuilder

class EntityUpdateDSL(val updateModel: EntityModel) : EntityBaseDSL() {
    override val builder = UpdateQueryBuilder()

    init {
        builder.on(getTableModelFromEntityModel(updateModel))

        updateModel.changedDataMap.forEach {
            val f = updateModel.fieldInfo[it.key]!!

            if (f.dbAutoGenerated) {
                return@forEach
            }

            val c = getColumnModelFromEntityFieldInfo(f)
            builder.set(c, it.value)
        }
    }

    fun set(f: EntityFieldInfo, source: EntityFieldInfo): EntityUpdateDSL {
        builder.set(getColumnModelFromEntityFieldInfo(f), getColumnModelFromEntityFieldInfo(source))
        return this
    }

    fun set(f: EntityFieldInfo, expr: SQLPart): EntityUpdateDSL {
        builder.set(getColumnModelFromEntityFieldInfo(f), expr)
        return this
    }

    fun from(model: EntityModel): EntityUpdateDSL {
        builder.from(getTableModelFromEntityModel(model))
        return this
    }

    fun where(conditions: () -> ExpressionBuilder): EntityUpdateDSL {
        builder.where(conditions())

        return this
    }
}