package io.github.notsyncing.lightfur.entity

class EntityFieldInfo(val entity: EntityModel, val inner: Inner) {
    data class Inner(val name: String, val dbColumn: String, val dbType: String,
                     val dbLength: Int, val dbNullable: Boolean, val dbDefaultValue: Any?,
                     val dbHasDefaultValue: Boolean, val dbPrimaryKey: Boolean,
                     val dbAutoGenerated: Boolean)
}