package io.github.notsyncing.lightfur.ql.tests.performance.toys

import io.github.notsyncing.lightfur.entity.EntityModel

class UserContactDetailsModel : EntityModel(table = "user_contact_info_details") {
    var id: Long by field("id", primaryKey = true, autoGenerated = true)

    var contactInfoId: Long by field("contact_info_id")

    var comment: String? by field("comment")
}